[global]
logfile = "/tmp/taskmaster.log"
loglevel = "INFO"
user = "oprosvir"

[program.test_sleep]
cmd = "/usr/bin/sleep 30"
autostart = true
workingdir = "/tmp"

[program.test_true]
cmd = "/usr/bin/true"
autostart = true

[program.test_false]
cmd = "/usr/bin/false"
autostart = true
startretries = 3

[program.test_workers]
cmd = "/usr/bin/sleep 30"
numprocs = 3
autostart = true

[program.test_nonexist]
cmd = "nonexisting"

[program.test_server]
cmd = "/usr/bin/python3 -m http.server 8080"
starttime = 3